name: JobforTech
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  convex_bottom_bar: ^3.2.0
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  grouped_list: ^5.1.2
  intl: ^0.18.1
  mobkit_dashed_border: ^0.0.5
  salomon_bottom_bar: ^3.3.2
  stylish_bottom_bar: ^1.0.3
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_native_splash:
  image: images/Group 17.png
  color: "#0371D8"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: images/IconApp.png
